### ISSUE TITLE
Any example ?

### ISSUE THREAD

**Issue by shubs** [tzwickl/passport-linkedin-api-v2#1]
Hey
First of all, thanks a lot for putting this out,
but I am not able to use it properly,
do you have any example of usage ?

Thanks

**Comment by tzwickl** [comment]
Hi @shubs, did you see the usage example in the README.md? For what exactly do you need an example? The authorization process with passport?

**Comment by shubs** [comment]
Sorry if wasn't clear enough, 
Yes I meant an example with passport authorization,

I saw the example in  README.md, wasn't able to figure out how to implement it in a passport auth
I was using in the same way as https://github.com/auth0/passport-linkedin-oauth2

**Comment by tzwickl** [comment]
@shubs Ahh ok, so you are looking for an example on how to use it with Javascript? I updated the README and added a usage example for Javascript like in the old oauth0 :) 
Hope that this will help you ;)
